update ci flow to move build and test steps inside docker container 3

diff --git a/.github/workflows/cypress-tests.yml b/.github/workflows/cypress-tests.yml
--- a/.github/workflows/cypress-tests.yml
+++ b/.github/workflows/cypress-tests.yml
@@ -34,8 +34,13 @@ jobs:
         cache-from: type=local,src=/tmp/.buildx-cache
         cache-to: type=local,dest=/tmp/.buildx-cache
 
+    - name: Ensure Docker image is available
+      run: |
+        docker pull formula1charts:latest || echo "Image not found remotely, using locally built image."
+
     - name: Start Django server in Docker container
       run: |
+        docker images
         docker run -d --name formula1charts-test -p 8000:8000 --env DJANGO_SETTINGS_MODULE=formula1charts.settings formula1charts:latest
 
     - name: Wait for Django server in container
